export interface TagItem {
  id: string
  name: string
}

export type TagCategoryKey = "main" | "theme" | "role" | "plot"

export interface TagCategory {
  key: TagCategoryKey
  label: string
  maxSelect: number
  items: TagItem[]
}

export const TAG_CATEGORIES: TagCategory[] = [
  {
    key: "main",
    label: "主分类",
    maxSelect: 1,
    items: [
      { id: "xianxia", name: "仙侠" },
      { id: "xuanhuan", name: "玄幻" },
      { id: "dushi", name: "都市" },
      { id: "yanqing", name: "言情" },
      { id: "kehuan", name: "科幻" },
      { id: "xuanyi", name: "悬疑" },
      { id: "wuxia", name: "武侠" },
      { id: "lishi", name: "历史" },
      { id: "youxi", name: "游戏" },
      { id: "junshi", name: "军事" },
      { id: "lingyi", name: "灵异" },
      { id: "tongren", name: "同人" },
      { id: "qihuan", name: "奇幻" },
      { id: "mopian", name: "末世" },
      { id: "chongsheng", name: "重生" },
    ],
  },
  {
    key: "theme",
    label: "主题",
    maxSelect: 2,
    items: [
      { id: "niyuxing", name: "逆袭" },
      { id: "fendou", name: "奋斗" },
      { id: "xiuzhen", name: "修真" },
      { id: "xuexing", name: "觉醒" },
      { id: "zhuiluo", name: "坠落" },
      { id: "chongzu", name: "冲族" },
      { id: "moushi", name: "谋士" },
      { id: "gongdou", name: "宫斗" },
      { id: "zhaitou", name: "宅斗" },
      { id: "chaonengli", name: "超能力" },
      { id: "mofa", name: "魔法" },
      { id: "tielu", name: "铁律" },
      { id: "xuewei", name: "学位" },
      { id: "shouni", name: "收逆" },
      { id: "baochou", name: "报仇" },
      { id: "shuangwen", name: "爽文" },
      { id: "nuanwen", name: "暖文" },
      { id: "tiyan", name: "甜言" },
      { id: "nuewen", name: "虐文" },
      { id: "shuimi", name: "水秘" },
      { id: "weixing", name: "伪形" },
      { id: "wuxianliu", name: "无线流" },
      { id: "xiuzhenliu", name: "修真流" },
      { id: "honghuang", name: "洪荒" },
      { id: "demolish", name: "破灭" },
      { id: "mogai", name: "膜改" },
      { id: "tiangai", name: "天改" },
      { id: "kuaichuan", name: "快穿" },
      { id: "chuanxue", name: "穿学" },
      { id: "shikongchuanxue", name: "时空穿越" },
      { id: "kehuanxingqiu", name: "科幻星球" },
      { id: "jijia", name: "机甲" },
      { id: "saibopeng", name: "赛博朋克" },
      { id: "xingji", name: "星际" },
      { id: "waixingren", name: "外星人" },
      { id: "tamende", name: "他们" },
      { id: "shaonian", name: "少年" },
      { id: "qingnian", name: "青年" },
      { id: "zhongnian", name: "中年" },
      { id: "laonian", name: "老年" },
      { id: "xuanmei", name: "悬美" },
      { id: "shengqi", name: "声起" },
      { id: "tianmei", name: "甜美" },
      { id: "baihe", name: "百合" },
      { id: "danmei", name: "耽美" },
      { id: "nvsheng", name: "女频" },
      { id: "nansheng", name: "男频" },
      { id: "junshi_zhanzheng", name: "战争" },
      { id: "tezhongbing", name: "特种兵" },
      { id: "jiandie", name: "间谍" },
      { id: "fanchuan", name: "反穿" },
      { id: "yijie", name: "异界" },
      { id: "xiushen", name: "修真" },
      { id: "lianqi", name: "炼器" },
      { id: "danfang", name: "丹方" },
      { id: "zhenfa", name: "阵法" },
      { id: "fuqi", name: "福气" },
      { id: "shangye", name: "商业" },
      { id: "jingji", name: "经济" },
      { id: "zhengzhi", name: "政治" },
      { id: "wenhua", name: "文化" },
      { id: "jiaoyu", name: "教育" },
      { id: "yiliao", name: "医疗" },
      { id: "falu", name: "法律" },
      { id: "dongwu", name: "动物" },
      { id: "zhiwu", name: "植物" },
      { id: "shenghuo", name: "生活" },
      { id: "jiating", name: "家庭" },
      { id: "aiqing", name: "爱情" },
      { id: "youyi", name: "友情" },
      { id: "qinqing", name: "亲情" },
      { id: "xueyuan", name: "学院" },
      { id: "zhichang", name: "职场" },
      { id: "yuanyuzhou", name: "元宇宙" },
      { id: "xuniwangluo", name: "虚拟网络" },
      { id: "quanxi", name: "全息" },
      { id: "xitong", name: "系统" },
      { id: "jifen", name: "积分" },
      { id: "renwu", name: "任务" },
      { id: "jiangli", name: "奖励" },
      { id: "shilian", name: "试炼" },
      { id: "shengji", name: "升级" },
      { id: "jineng", name: "技能" },
      { id: "tianfu", name: "天赋" },
      { id: "zhuangbei", name: "装备" },
    ],
  },
  {
    key: "role",
    label: "角色",
    maxSelect: 2,
    items: [
      { id: "qiangzhe", name: "强者" },
      { id: "feiwu", name: "废物" },
      { id: "yingxiong", name: "英雄" },
      { id: "fanpai", name: "反派" },
      { id: "nuzhujiao", name: "女主角" },
      { id: "nanzhujiao", name: "男主角" },
      { id: "xuetu", name: "学徒" },
      { id: "daoshi", name: "导师" },
      { id: "mengshou", name: "萌兽" },
      { id: "shouhu", name: "守护" },
      { id: "shaonv", name: "少女" },
      { id: "shaonian_zhu", name: "少年" },
      { id: "xinbing", name: "新兵" },
      { id: "jiangling", name: "将领" },
      { id: "dixi", name: "帝系" },
      { id: "wangye", name: "王爷" },
      { id: "gongzhu", name: "公主" },
      { id: "taizi", name: "太子" },
      { id: "zongcai", name: "总裁" },
      { id: "mishu", name: "秘书" },
      { id: "yisheng", name: "医生" },
      { id: "jianshe", name: "建设" },
      { id: "xuemei", name: "学妹" },
      { id: "xuezha", name: "学霸" },
      { id: "xiaoyuan", name: "校园" },
      { id: "laoshi", name: "老师" },
      { id: "jizhe", name: "记者" },
      { id: "jingshen", name: "精神" },
      { id: "hugong", name: "护工" },
      { id: "shibing", name: "士兵" },
      { id: "heike", name: "黑客" },
      { id: "tante", name: "探特" },
      { id: "teqin", name: "特勤" },
      { id: "jianzhu", name: "建筑" },
      { id: "nongmin", name: "农民" },
      { id: "gongren", name: "工人" },
      { id: "qihuan_ren", name: "奇幻人" },
      { id: "jingguai", name: "精怪" },
      { id: "yaomo", name: "妖魔" },
      { id: "xianren", name: "仙人" },
      { id: "shenming", name: "神明" },
      { id: "guizu", name: "贵族" },
      { id: "pingmin", name: "平民" },
      { id: "nuli", name: "奴隶" },
      { id: "nvwu", name: "女巫" },
      { id: "nanwu", name: "男巫" },
    ],
  },
  {
    key: "plot",
    label: "情节",
    maxSelect: 2,
    items: [
      { id: "chuanxue_", name: "穿越" },
      { id: "zhongshen", name: "重生" },
      { id: "bianxing", name: "变性" },
      { id: "shixiong", name: "失忆" },
      { id: "jueqi", name: "崛起" },
      { id: "fuzhi", name: "复制" },
      { id: "tihuan", name: "替换" },
      { id: "weizhuang", name: "伪装" },
      { id: "jianbao", name: "鉴宝" },
      { id: "xunbao", name: "寻宝" },
      { id: "taosheng", name: "逃生" },
      { id: "jianyu", name: "监狱" },
      { id: "mousha", name: "谋杀" },
      { id: "fusheng", name: "复生" },
      { id: "huigui", name: "回归" },
      { id: "yinmou", name: "阴谋" },
      { id: "panbian", name: "叛变" },
      { id: "jieceng", name: "阶层" },
      { id: "shengji_", name: "升级" },
      { id: "tupo", name: "突破" },
      { id: "jingsu", name: "竞速" },
      { id: "bisai", name: "比赛" },
      { id: "jieri", name: "节日" },
      { id: "wanhui", name: "晚会" },
      { id: "hunli", name: "婚礼" },
      { id: "sangli", name: "丧礼" },
      { id: "jihui", name: "集会" },
      { id: "zimu", name: "子目" },
      { id: "tiaozhan", name: "挑战" },
      { id: "maoxian", name: "冒险" },
    ],
  },
]

export function buildPrompt(
  selectedTags: Record<TagCategoryKey, TagItem[]>,
  topic: string,
): string {
  const parts: string[] = []
  for (const cat of TAG_CATEGORIES) {
    const tags = selectedTags[cat.key]
    if (tags.length > 0) {
      parts.push(`${cat.label}：${tags.map((t) => t.name).join("、")}`)
    }
  }
  if (topic.trim()) {
    parts.push(`补充描述：${topic.trim()}`)
  }
  return parts.join("\n")
}
